language: node_js
node_js: 12
script: npm run build-release
  
deploy:
  - provider: releases
    file: garage-door-opener-*.tgz
    token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
    on:
      tags: true
    edge: true

deploy:
  - provider: npm
    api_key: $NPM_TOKEN
    email: giles@roadnight.name
    src: node-red-contrib-garage-door
    on:
      tags: true
    edge: true